version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

  pr-offline-reviewer:
    build: .
    container_name: pr-offline-reviewer
    ports:
      - "5000:5000"
    environment:
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_models:
